name: tarea2-nlp
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - numpy =1.25.2
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - rich
  - pip:
      - unidecode
      - transformers
      - datasets
      - lyricsgenius
      - python-dotenv
