name: tarea2-nlp
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - torch
      - transformers
      - datasets
      - lyricsgenius
      - python-dotenv
