name: tarea2-nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - numpy=1.25.2
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - rich
  - ftfy
  - spacy
  - pip:
      - unidecode
      - transformers == 4.38.0
      - datasets
      - lyricsgenius
      - python-dotenv
      - peft
      - accelerate
      - bitsandbytes
      - nltk
      - wandb